site_name: Setup ISC BIND 9
site_description: "Установка и настройка сервера разрешения имен"
site_url: http://gvc-tex-docs-01.gvc.oao.rzd/
copyright: Copyright &copy; <a href="https://github.com/D34m0nN0n3">Dmitriy Prigoda</a>.

repo_name: "ansible-ssr-dns"
repo_url: "https://github.com/D34m0nN0n3/ansible-ssr-dns"

use_directory_urls: false

nav:
    - Общее описание: 'index.md'
    - Роли:
      - ISC BIND 9: 'roles/dns_server.md'
      - resolv.conf: 'roles/dns_client.md'
    - Дополнительные материалы: 'seealso.md'

plugins:
    - search
    - git-revision-date
    - pdf-export:
        verbose: true
        media_type: print
        combined: true
        combined_output_path: 'pdf/Установка_и_настройка_сервера_разрешения_имен.pdf'
        theme_handler_path: theme-handler/material.py

theme:
  name: material
  custom_dir: 'material'
  palette:
    scheme: default
    primary: blue grey
    accent: red
  logo: 'assets/img/logo/logo.svg'
  favicon: 'assets/img/favicon/favicon.ico'
  language: 'ru'
  feature:
    tabs: false

extra:
  search:
    language: 'ru, en'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/D34m0nN0n3/ansible-ssr-dns/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab-lb-01.gvc.oao.rzd/D34m0nN0n3/ansible-ssr-dns/
    
extra_css:
  - material/assets/css/main.css
  - material/assets/libs/magnific-popup/magnific-popup.css
  - material/assets/css/pdf.css

extra_javascript:
  - material/assets/libs/jquery/jquery-3.4.0.min.js
  - material/assets/libs/magnific-popup/jquery.magnific-popup.min.js
  - material/assets/js/main.js

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_blockdiag:
      format: svg
  - markdown_include.include
