---
- hosts: all
  gather_facts: true

  tasks:
    - name: ISC bind install
      include_role:
        name: infra-system.linux.isc-bind-setup

    - name: Configure DNS client with DNSMASQ
      include_role:
        name: infra-system.linux.os.dnsmasq-resolver
...
