---
# Sets the number of times the resolver will send a query to its name servers before giving up and returning an error to the calling application
dns_attempts: '3'
# Sets the amount of time the resolver will wait for a response from a remote name server before retrying the query via a different name server
dns_timeout: '2'
# Sets a threshold for the number of dots which must appear in a name
dns_ndots: '1'
# The directive is an obsolete name for the search
dns_domain: "{{ ansible_domain }}"
# Search list for host-name lookup
dns_search: ['{{ ansible_domain }}']
# Name server IP address
nameserver: ['1.1.1.1','8.8.8.8']