---
- name: Check configuration
  block:
    - name: Check named.conf
      command: named-checkconf /etc/named.conf
      register: check_conf_result

    - name: Check zones
      command: named-checkconf -z
      register: check_zones_result

- name: Check services exists
  block:
    - name: Check service facts
      service_facts:

    - name: Enable service ISC BIND and ensure it is not masked
      systemd:
        name: named-chroot
        state: started
        enabled: yes
        masked: no
      register: result
      when: ansible_facts.services['named-chroot.service'] is defined and ansible_facts.services['named-chroot.service'].status == 'disabled'

    - name: Enable bind_exporter service
      systemd:
        name: bind_exporter
        state: started
        enabled: yes
        masked: no
      register: result
      when: ansible_facts.services['bind_exporter.service'] is defined and ansible_facts.services['named-chroot.service'].state == 'running'

    - name: Enable node_exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
        masked: no
      register: result
      when: ansible_facts.services['node_exporter.service'] is defined
  when: (check_conf_result.rc == 0) and (check_zones_result.rc == 0)

- name: Mail report
  block:
    - name: RCPT
      set_fact: 
        mail_rcpt_to: bind_cont_mail
      when: mail_rcpt_to is undefined

    - name: FROM
      set_fact: 
        mail_from: "{{ ansible_user_id + @ + ansible_domain }}"
      when: mail_from is undefined

    - name: Send mail report
      mail:
        host: "{{ mail_host }}"
        port: "{{ mail_port | default('25') }}"
        from: "{{ mail_from }}"
        to: "{{ mail_rcpt_to }}"
        subject: 'Ansible-report: ISC BIND setup.'
        body: "{{ lookup('template', 'templates/mail_body.j2') }}"
      ignore_errors: yes
      run_once: True
  when: mail_host is defined
...
