---
- name: Check configuration
  block:
    - name: Check named.conf
      command: named-checkconf /etc/named.conf
      register: check_conf_result
      ignore_errors: true

    - name: Check zones
      command: named-checkconf -z
      register: check_zones_result
      ignore_errors: true

- name: Check services exists
  block:
    - name: Check service facts
      service_facts:

    - name: Restart service ISC BIND if running
      assert:
        that:
          - "'{{ ansible_facts.services['named-chroot.service'].state }}' == 'running'"
      notify:
        - Restart_BIND

    - name: Enable service ISC BIND and ensure it is not masked
      systemd:
        name: named-chroot
        state: started
        enabled: yes
        masked: no
      register: result
      when: ansible_facts.services['named-chroot.service'] is defined and ansible_facts.services['named-chroot.service'].status == 'disabled'

    - name: Enable bind_exporter service
      systemd:
        name: bind_exporter
        state: started
        enabled: yes
        masked: no
      register: result
      when: ansible_facts.services['bind_exporter.service'] is defined and ansible_facts.services['named-chroot.service'].state == 'running'

    - name: Enable node_exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
        masked: no
      register: result
      when: ansible_facts.services['node_exporter.service'] is defined
  when: (check_conf_result.rc == 0) and (check_zones_result.rc == 0)
...
