---
- name: Include task for install ISC BIND
  include: install.yml

- name: Include task for configure ISC BIND
  include: configure.yml

- name: Include task for restore zones from git ISC BIND
  include: restore.yml
  when: bind_restore_last_conf | bool == true

- name: Include task for enable and start ISC BIND
  include: enable.yml

- name: Include task for generate ans send mail report
  include: report.yml
  when: mail_host is defined and mail_port is defined and (mail_rcpt_to is defined or bind_cont_mail is defined)
...
