---
- name: Check run scaleup tasks
  set_fact:
    scaleup: true
  when: (ansible_play_hosts_all | map('extract', hostvars, 'new_slave') | select | list ) or
        (groups.new_slaves | default([]) | length != 0)

- name: Include task for scaleup ISC BIND
  include: scaleup_slaves.yml
  when: scaleup is defined and (scaleup | bool == true)

- name: Include task for install ISC BIND
  include: install.yml

- name: Include task for configure ISC BIND
  include: configure.yml

- name: Include task for restore zones from git ISC BIND
  include: restore.yml
  when: bind_restore_last_conf | bool == true

- name: Include task for enable and start ISC BIND
  include: enable.yml

- name: Include task for generate ans send mail report
  include: report.yml
  when: mail_host is defined and (mail_rcpt_to is defined or bind_cont_mail is defined)
...
