galaxy_info:
  role_name: infra-system.linux.isc-bind-setup
  author: Dmitriy Prigoda
  description: Setup a ISC BIND 9 DNS service on Centos/RHEL7/8

  license: license (GPL-3.0-only)

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags: 
    - dns
    - bind
    - named
    - nameserver
    - networking
    - system

dependencies: []
